basic:
    name: 'https://www.opploans.com batch 4'
    environments:
        production: 'https://www.opploans.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /rates-and-terms/oklahoma
        - /rates-and-terms/oregon
        - /rates-and-terms/rhode-island
        - /rates-and-terms/south-carolina
        - /rates-and-terms/tennessee
        - /rates-and-terms/texas
        - /rates-and-terms/utah
        - /rates-and-terms/virginia
        - /rates-and-terms/washington
        - /rates-and-terms/wyoming
    monitoring:
        days: {  }
        type: daily
        schedule_time: '03:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
