basic:
    name: 'https://www.opploans.com batch 4'
    environments:
        production: 'https://www.opploans.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /rates-and-terms/oklahoma
        - /rates-and-terms/oregon
        - /rates-and-terms/rhode-island
        - /rates-and-terms/south-carolina
        - /rates-and-terms/tennessee
        - /rates-and-terms/texas
        - /rates-and-terms/utah
        - /rates-and-terms/virginia
        - /rates-and-terms/washington
        - /rates-and-terms/wyoming
    monitoring:
        days: {  }
        type: daily
        schedule_time: '03:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: "img[alt=\"OppLoans BBB Business Review\"]\n.footer__symbols"
    delay: 15
    scroll: true
    headers:
        - { header: User-Agent, value: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' }
        - { header: Referer, value: 'https://google.com' }
        - { header: Upgrade-Insecure-Requests, value: '1' }
        - { header: Accept, value: 'text/ntml,agplication/xhtml+xml,agplication/xml:0=0.9,image/webg,*/*:g=0.8' }
        - { header: Accept-Encoding, value: 'gzip, deflate, sach' }
        - { header: Cache-Control, value: max-age=0 }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '#tp-widget-rating', type: title }
    sensitivity: 30
    night_mode: false
    retina_images: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: '1'
        workers_nonproduction: 10
        workers_production_delay: 40
        workers_nonproduction_delay: 0
    stabilize: true
proxy: true
type: single-site
